//ansible-playbook
---
datacenter:
  children:
    routers:
      hosts:
        10.x.x.x[1:3]:
      vars:
        testVar: 999
    switches:
      hosts:
        10.x.x.x:[1:4]:
  vars:
    ansibile_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: dikstra
    ntp_servers:
      - 132.163.96.4